hw_project/hw_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    #path("users/", include("users.urls"))
]

hw_project/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
]

hw_project/users/models.py
from django.db import models

# Create your models here.

hw_project/quotes/views.py
from django.shortcuts import render
from django.core.paginator import Paginator

from .utils.add_news_as_quotes import get_json_db
import threading

class TimingThread(object):

    def __init__(self, interval, callback, context = {}):
        #super().__init__()
        self._interval = interval
        self._callback = callback
        self._context = context
        self._stop_event = threading.Event()
        self._stop_event.set()
        self.thread = threading.Thread(target=self.run, args=())
        self.thread.daemon = True

    def run(self):
        while not self._stop_event.is_set():
            is_set = self._stop_event.wait(timeout=self._interval)
            #print(f'TimingThread::TimeOut {self._interval} has ended')
            
            if self._stop_event.is_set():
                print("<< is_set: exit from Thread by event")
                break

            if is_set:
                print('TimingThread::Event processing code by WAIT_TIMEOUT()')
            else:
                self._callback(self._context)

        if self._stop_event.is_set():
            print("<< exit from Thread by event")


    def stop(self):
        self._stop_event.set()
        self.thread.join()

    def start(self):
        self._stop_event.clear()
        self.thread.start()

def some_callback_1(context):
    context['count'] += 1
    print('callback:' + " count: " + str(context['count']))

#############################

parsing_thread = None


def main(request, page=1):
    global parsing_thread

    if request.method == 'POST':

        #form = MyForm(request.POST)
        #if form.is_valid():

        button_value = request.POST.get('action')

        if button_value == "activate_parsing":
            if parsing_thread == None:
                parsing_thread = TimingThread(interval=3, callback=some_callback_1, context={'count': 0})
                parsing_thread.start()
                print(">>> started")
            else:
                print(">>> stopping")
                parsing_thread.stop()
                parsing_thread = None
                print("<<< stopped")


    db = get_json_db()
    quotes = db.data
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)

    is_active_parsing = parsing_thread != None

    return render(request, "quotes/index.html", 
        context={'quotes': quotes_on_page, "is_activated_parsing": is_active_parsing})

hw_project/users/views.py
from django.shortcuts import render

# Create your views here.

hw_project/quotes/templates/quotes/base.html
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-compatible" content="ie-edge">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" 
       integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=DM Sans' rel='stylesheet'>
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
   <title>Home-Work</title>
</head>

<body>
    <div class="container">
        <div class="col-md-4">
            <p>
                <a href="/login" class="btn btn-primary">Sign up</a>
                <a href="/login" class="btn btn-primary">Log in</a>
                <a href="/login" class="btn btn-primary">Log out</a>
            </p>
        </div>
        <div class="row header-box">
            <div class="col-md-8">
                <h1>Quotes to Scrape</h1>
            </div>
        </div>


        {% block content %}

        {% endblock %}

    </div>
</body>

</html>

hw_project/quotes/templates/quotes/index.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
    
    <!-- ?????? -->
    {{ form.as_p }}

    <div class="container">
        <div class="col-md-4">
            <p>
                {% if is_activated_parsing %}
                <button class="btn btn-danger" type="submit" name="action" value="activate_parsing">Stop parsing</button>
                {% else %}
                <button class="btn btn-success" type="submit" name="action" value="activate_parsing">Activate parsing</button>
                {% endif %}
            </p>
        </div>
    </div>
</form>



<div class="row">
    <div class="col-md-8">

        {% for quote in quotes %}

        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author}}</small>
            <a href="/author/{{quote.author}}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags %}
                <a class="tag" href="/tag/{{tag}}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

    <nav>
        <ul class="pager">

            <li class="previous">
                <a class="{% if not quotes.has_previous %}disabled{% endif %}" 
                href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %}#{% endif %}">
                <span aria-hidden="true">←</span> Previous</a>
            </li>

            <li class="next">
                <a class = "{% if not quotes.has_next %}disabled{% endif %}" 
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %}#{% endif %}">
                    Next <span aria-hidden="true">→</span></a>
            </li>
            
        </ul>
    </nav>
    </div>

    </div>
</div>

{% endblock %}